name: Build on Server

on:
  push:
    branches:
      - main

jobs:
  build-on-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run pnpm build on remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            cd /www/wwwroot/pppi-gallery
            git reset --hard origin/main
            git pull
            npm install
            pm2 reload pppi-gallery 
